app.config(["$stateProvider","$urlRouterProvider",function($stateProvider,$urlRouterProvider){
			$urlRouterProvider.otherwise('vip');
			$stateProvider
			.state("vip",{
				url:"/vip",
				templateUrl:"1会员中心-index.html"
			})
			.state("personal2",{
				url:"/personal2",
				templateUrl:"2个人资料.html"
			})
			.state("personal3",{
				url:"/personal3",
				templateUrl:"3个人资料-修改.html"
			})
			.state("personal4",{
				url:"/personal4",
				templateUrl:"4个人资料-修改密码.html"
			})
			.state("personal5",{
				url:"/personal5",
				templateUrl:"5个人资料-修改密码-2.html"
			})
			.state("personal6",{
				url:"/personal6",
				templateUrl:"6个人资料-修改密码成功.html"
			})
			.state("personal7",{
				url:"/personal7",
				templateUrl:"7个人资料-修改手机号.html"
			})
			.state("vipClub8",{
				url:"/vipClub8",
				templateUrl:"8会员俱乐部.html"
			})
			.state("vipClub9",{
				url:"/vipClub9",
				templateUrl:"9会员俱乐部-会员特权.html"
			})
			.state("vipClub10",{
				url:"/vipClub10",
				templateUrl:"10会员俱乐部-我的积分.html"
			})
			.state("vipClub11",{
				url:"/vipClub11",
				templateUrl:"11会员俱乐部-我的优惠券.html"
			})
			.state("vipClub12",{
				url:"/vipClub12",
				templateUrl:"12会员俱乐部-积分密码.html"
			})
			.state("vipClub13",{
				url:"/vipClub13",
				templateUrl:"13会员俱乐部-实体卡激活.html"
			})
			.state("vipClub14",{
				url:"/vipClub14",
				templateUrl:"14会员俱乐部-我的推荐人.html"
			})
			.state("order15",{
				url:"/order15",
				templateUrl:"15我的订单-待支付.html"
			})
			.state("myServer16",{
				url:"/myServer16",
				templateUrl:"16我的服务-出行服务.html"
			})
			.state("myServer17",{
				url:"/myServer17",
				templateUrl:"17我的服务-线下服务网络.html"
			})
			.state("myServer18",{
				url:"/myServer18",
				templateUrl:"18我的服务-门市详情.html"
			})
			.state("offerMessage20",{
				url:"/offerMessage20",
				templateUrl:"20常用信息.html"
			})
			.state("offerMessage21",{
				url:"/offerMessage21",
				templateUrl:"21常用信息-常用地址.html"
			})
			.state("offerMessage22",{
				url:"/offerMessage22",
				templateUrl:"22常用信息-添加常用地址.html"
			})
			.state("offerMessage23",{
				url:"/offerMessage23",
				templateUrl:"23常用信息-增加常用旅客.html"
			})
			.state("personalX1",{
				url:"/personalX1",
				templateUrl:"3个人资料-修改-修改姓名.html"
			})
			.state("personalX2",{
				url:"/personalX2",
				templateUrl:"3个人资料-修改-修改身份证.html"
			})
			.state("personalX3",{
				url:"/personalX3",
				templateUrl:"3个人资料-修改-修改邮箱.html"
			})
			.state("offerMessage24",{
				url:"/offerMessage24",
				templateUrl:"24常用信息-新增发票.html"
			})
			.state("collection",{
				url:"/collection",
				templateUrl:"25我的收藏.html"
			})
			.state("history",{
				url:"/history",
				templateUrl:"26浏览历史.html"
			})
			.state("comment",{
				url:"/comment",
				templateUrl:"27我的点评.html"
			})
			
			.state("commentRule",{
				url:"/commentRule",
				templateUrl:"28点评规则.html"
			})
			
			.state("contract",{
				url:"/contract",
				templateUrl:"29合同验真.html"
			})
			.state("travel",{
				url:"/travel",
				templateUrl:"30爱旅行.html"
			})
			.state("travel1",{
				url:"/travel1",
				templateUrl:"31爱旅行-暂存.html"
			})
			.state("travel2",{
				url:"/travel2",
				templateUrl:"32爱旅行-游记.html"
			})
			.state("find",{
				url:"/find",
				templateUrl:"33发现.html"
			})
			.state("myMessage",{
				url:"/myMessage",
				templateUrl:"34我的消息.html"
			})
			.state("message",{
				url:"/message",
				templateUrl:"35系统消息.html"
			})
			.state("forecast",{
				url:"/forecast",
				templateUrl:"36天气预报.html"
			})
			.state("service",{
				url:"/service",
				templateUrl:"37在线客服.html"
			})
			.state("edit",{
				url:"/edit",
				templateUrl:"38设置.html"
			})
			.state("feature",{
				url:"/feature",
				templateUrl:"39新特性.html"
			})
		}]);
